name: Testing Google Pixel device
on: 
  push:
    branches: master
  pull_request:
    branches: master
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    - name: Install dependencies
      run: npm install
    - name: Run all tests
      run: npm run wdio-google-pixel
      env:
          CI: true
          USERNAME: ${{ secrets.USERNAME }}
          ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
    - uses: actions/checkout@v2
      if: always()
      with:
        repository: chabanstas/browserstack_test
        ref:  report
        path: ./docs
        
    - name: Push to repository
      uses: cpina/github-action-push-to-another-repository@main
      if: always()
      env:
        API_TOKEN_GITHUB: ${{ secrets.ACTIONS_TOKEN }}
      with:
        destination-github-username: 'chabanstas'
        destination-repository-name: 'browserstack_test'
        user-email: stanislav.chaban.02@gmail.com
        target-branch: main
